name: time_peace_project
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  action_slider: ^0.7.0
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.2
  firebase_app_check: ^0.2.2+7
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_core_web: ^2.17.2
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  google_fonts: ^6.2.0
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.6
  intl: ^0.19.0
  like_button: ^2.0.5
  lottie: ^3.1.1
  order_tracker: ^0.0.2
  razorpay_flutter: ^1.3.7
  timelines: ^0.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/background_image.webp
    - assets/background_watch.avif
    - assets/background.jpg
    - assets/cartpng.png
    - assets/Google_logo.png
    - assets/sign-up wallpaper.jpg
    - assets/1713BM02_1.jpg
    - assets/men_with_watch.webp
    - assets/women_with_watch.jpg
    - assets/kids_with_watch.png
    - assets/workwear_banner_1.webp
    - assets/animations/Animation - grid_loading.json
    - assets/black_watch_11_.jpg

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
